spring.application.name=gestion-ordre-fabrication

server.port=9090

# =========================
# DATABASE CONFIG (MySQL)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3307/backend_suj10?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (optionnel mais recommandé avec Spring Boot récent)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# DEVTOOLS (optionnel)
# =========================
spring.devtools.restart.enabled=true